apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -o .k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: demo
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: demo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -o .k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: demo
    spec:
      containers:
      - env:
        - name: APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              key: APPLICATION_NAME
              name: demo--env
        - name: EUREKA_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: EUREKA_SERVER_URL
              name: demo--env
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              key: SERVER_PORT
              name: demo--env
        image: microservice-gowise/demo
        imagePullPolicy: ""
        name: demo
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
