apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -o .k8s
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: python-service
  name: python-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: python-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -o .k8s
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: python-service
    spec:
      containers:
      - image: microservice-gowise/python-service
        imagePullPolicy: ""
        name: python-service
        ports:
        - containerPort: 8001
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
