global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:8080']
    metrics_path: /actuator/prometheus

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8081']
    metrics_path: /actuator/prometheus

  - job_name: 'demo'
    static_configs:
      - targets: ['demo:8082']
    metrics_path: /actuator/prometheus

  - job_name: 'discovery-server'
    static_configs:
      - targets: ['discovery-server:8761']
    metrics_path: /actuator/prometheus

  - job_name: 'python-service'
    static_configs:
      - targets: ['python-service:8001']

  - job_name: 'go-service'
    static_configs:
      - targets: ['go-service:8002']
    metrics_path: /metrics
