[project]
name = "python-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "py-eureka-client>=0.11.13",
    "uvicorn[standard]>=0.34.3",
]
