name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-java-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [discovery-server, admin-service, api-gateway, demo]
    defaults:
      run:
        working-directory: ${{ matrix.service }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests
      - name: Run unit & integration tests
        run: ./mvnw test

  build-python-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install uv && uv pip install --system --no-cache .
      - name: Lint
        run: pip install flake8 && flake8 server.py

  build-go-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build
        run: go build -v ./...

  docker-compose-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:24.0.5-dind
        options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and run all services
        run: docker-compose up --build -d
      - name: Wait for services to be healthy
        run: sleep 60
      - name: Test API Gateway health
        run: curl --fail http://localhost:8081/health || exit 1
      - name: Test Prometheus
        run: curl --fail http://localhost:9090/-/ready || exit 1
      - name: Tear down
        run: docker-compose down